---
- name: Create and configure a Linux EC2 instance
  hosts: localhost
  gather_facts: false
  vars_files:
    - defaults/create_linux_ec2_instance_defaults.yml
  tasks:

    - name: Assert required variables are supplied
      ansible.builtin.assert:
        that:
          - aws_region is defined and aws_region|length > 0
          - ami_id is defined and ami_id|length > 0
          - ec2_name_tag is defined and ec2_name_tag|length > 0
          - iam_instance_profile_arn is defined and iam_instance_profile_arn|length > 0
        fail_msg: "One or more required variables (aws_region, ami_id, ec2_name_tag, iam_instance_profile_arn) are missing."

    - name: Lookup default VPC if vpc_id not provided
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          isDefault: true
      register: default_vpc_info
      when: vpc_id == "auto"

    - name: Set vpc_id to default if not provided
      ansible.builtin.set_fact:
        vpc_id: "{{ default_vpc_info.vpcs[0].vpc_id }}"
      when: vpc_id == "auto" and default_vpc_info.vpcs | length > 0

    - name: Discover security group {{ monitoring_host_sg_name }}
      amazon.aws.ec2_security_group_info:
        region: "{{ aws_region }}"
        filters:
          group-name: "{{ monitoring_host_sg_name }}"
          vpc-id: "{{ vpc_id }}"
      register: sg_info

    - name: Fail if security group not found {{ monitoring_host_sg_name }}
      ansible.builtin.assert:
        that:
          - sg_info.security_groups | length > 0
        fail_msg: "Security group '{{ monitoring_host_sg_name }}' not found in region {{ aws_region }}. Cannot proceed."

    - name: Set security group ID
      ansible.builtin.set_fact:
        sg_id: "{{ sg_info.security_groups[0].group_id }}"

    - name: Lookup default subnet if subnet_id not provided
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          defaultForAz: true
          vpc-id: "{{ vpc_id }}"
      register: default_subnet_info
      when: subnet_id == "auto"

    - name: Set subnet_id to default if not provided
      ansible.builtin.set_fact:
        subnet_id: "{{ default_subnet_info.subnets[0].id }}"
      when: subnet_id == "auto" and default_subnet_info.subnets | length > 0

    - name: Set derived variables
      ansible.builtin.set_fact:
        key_name: "{{ ec2_name_tag }}-linux-ec2-key"

    - name: Create EC2 key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        state: present
      register: keypair_result

    - name: Launch and configure EC2 instance (with cleanup on failure)
      block:
        - name: Launch EC2 instance
          amazon.aws.ec2_instance:
            name: "{{ ec2_name_tag }}"
            key_name: "{{ key_name }}"
            instance_type: "{{ instance_type }}"
            image_id: "{{ ami_id }}"
            region: "{{ aws_region }}"
            subnet_id: "{{ subnet_id }}"
            security_group: "{{ sg_id }}"
            iam_instance_profile: "{{ iam_instance_profile_arn }}"
            wait: true
            wait_timeout: 500
            state: running
            count: 1
            volumes:
              - device_name: /dev/sda1
                ebs:
                  volume_type: "{{ root_volume_type }}"
                  volume_size: "{{ root_volume_size | int }}"
                  delete_on_termination: "{{ root_volume_delete_on_termination | bool }}"
                  encrypted: "{{ root_volume_encrypted | bool }}"
            tags:
              Name: "{{ ec2_name_tag }}"
          register: ec2_result

        - name: Set instance ID and derived facts
          ansible.builtin.set_fact:
            launched_instance_id: "{{ ec2_result.instances[0].instance_id }}"

        - name: Associate Elastic IP (optional)
          when: associate_eip | bool
          amazon.aws.ec2_eip:
            region: "{{ aws_region }}"
            state: present
            device_id: "{{ launched_instance_id }}"
          register: eip_result

        - name: Store private key in Vault
          ansible.builtin.include_role:
            name: manage_secret
          vars:
            manage_secret_action: write
            manage_secret_path: "linux/{{ launched_instance_id }}"
            manage_secret_payload:
              private_key: "{{ keypair_result.key.private_key }}"

        - name: Output instance info
          ansible.builtin.debug:
            msg:
              - "Instance ID: {{ ec2_result.instances[0].instance_id }}"
              - "Instance info: {{ ec2_result.instances }}"
              - "Elastic IP: {{ (associate_eip | bool) | ternary(eip_result, 'Not associated') }}"

      rescue:
        - name: Delete EC2 key pair if created
          amazon.aws.ec2_key:
            name: "{{ key_name }}"
            region: "{{ aws_region }}"
            state: absent
          ignore_errors: true

        - name: Delete EC2 instance if created
          when: ec2_result is defined and ec2_result.instances is defined and ec2_result.instances | length > 0
          amazon.aws.ec2_instance:
            instance_ids: "{{ ec2_result.instances[0].instance_id }}"
            region: "{{ aws_region }}"
            state: absent
            wait: true
          ignore_errors: true

        - name: Output cleanup info
          ansible.builtin.debug:
            msg: "Cleanup attempted for all created resources due to failure."
