---
collections:
  - name: community.hashi_vault
    version: ">=4.0.0"
  - name: amazon.aws
    version: ">=10.1.2"
  - name: community.crypto
    version: ">=2.17.0"
  - name: community.general
    version: ">=11.4.1"
  - name: prometheus.prometheus
    version: ">=0.27.0"
